CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    datecreate date NOT NULL
    
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, datecreate)
    VALUES('Me primeiro api rest', 1, 'Usando Javascript', '2021-03-13');

INSERT INTO projects(name, priority, description, datecreate)
    VALUES('Primeiro update do app', 1, 'implementar babel', '2021-03-14');

INSERT INTO projects(name, priority, description, datecreate)
    VALUES('Segundo update do app', 2, 'implementar sequelize', '2021-03-15');

--INSERIR DATA PARA A TAREFA
INSERT INTO tasks(name, done, projectid)
    VALUES('Baixar VueJs', false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES('Criar a UI', false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES('Download Flutter', false, 2);

INSERT INTO tasks(name, done, projectid)
    VALUES('Projetar a UI', false, 2);